name: Android CI

on:
  push:
  #  branches:    
  #    - master
  # Sequence of patterns matched against refs/tags
    tags:        
      - v2.*
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    #runs-on: ubuntu-latest
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v4.1.1
      with:
         ref: 'master'
         
    #- name: Set up JDK 17
    #  uses: actions/setup-java@v3
    #  with:
    #     java-version: '17'
    #     distribution: 'temurin'

    #- name: Setup Android SDK
    #  uses: android-actions/setup-android@v3

    #- name: Update submoudule
    #  shell: bash
    #  run: |
    #     git submodule update --init
      
    #- name: Build with Gradle
    #  run: ./gradlew :app:assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Test
        path: ${{github.workspace}}/README.md

    #- name: Release Upload
    #  uses: MHSanaei/upload-release-action@2.8.0
    #  with:
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    file: ${{github.workspace}}/app/build/outputs/apk/release/app-release.apk
    #    tag: ${{ github.ref }}
    #    overwrite: true
    #    file_glob: true
    #- name: Upload apk to release
    #  uses: svenstaro/upload-release-action@v2
    #  with:
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    file: ${{github.workspace}}/app/build/outputs/apk/release/app-release.apk
    #    tag: ${{ github.ref }}
    #    overwrite: true
    #    file_glob: true
    #  uses: d1ceward/draft-assets-release-action@v2.1.0
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    files: |
    #       ${{github.workspace}}/app/build/outputs/apk/release/app-release.apk     
